server:
  port: 10086 #eureka????
spring:
  application:
    name: eureka-web-server #eureka?????????
eureka:
  server:
    enable-self-preservation: false # Eureka????????????true??/false????????????????????????????????á?
    eviction-interval-timer-in-ms: 5000 # ??????Ч????????
  client:
    fetch-registry: false # ?????????????????嵥???????????????????
    register-with-eureka: true # ??????????????
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
#订单系统 购物车系统 搜索系统 认证系统